"""add columns to table

Revision ID: 008ce6713df5
Revises: 67f5d67aea55
Create Date: 2023-09-22 12:21:46.684533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008ce6713df5'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
